config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :settings
  resources :events do
    collection do
      get "list"
      get "love"
    end
  end
  
  
  root 'events#list'

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :image, AvatarUploader
  
  
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:list]
  before_action :authenticate_admin!, except: [:list]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end
  
  def list
    @events = Event.order "fire_at"
    @setting = Setting.first
    render :layout=>false
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def love
    render :layout=>false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :image, :fire_at, :desc)
    end
    
    def authenticate_admin!
      if current_user != User.first
        redirect_to "/"
      end
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: [:list]
  

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end
    
    def authenticate_admin!
      if current_user != User.first
        redirect_to "/"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:head, :foot, :title,:footer_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image) %>
  </div>
  <div class="form-group">
    <%= f.label :fire_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :fire_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fire_at) %>
  </div>
  <div class="form-group">
    <%= f.label :desc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:desc) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:fire_at) %></th>
      <th><%= model_class.human_attribute_name(:desc) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.title %></td>
        <td><%= event.image %></td>
        <td><%= event.fire_at %></td>
        <td><%= event.desc %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/list.html.erb
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%=@setting.head || "时间轴"%></title>
<link rel="stylesheet" href="/main.css" />
<link rel="stylesheet" href="/style.css" />
<style type="text/css">
h2.top_title{border-bottom:none;background:none;text-align:center;line-height:32px; font-size:20px}
h2.top_title span{font-size:12px; color:#666;font-weight:500}
</style>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.easing-1.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />


</head>

<body>

<h2 class="top_title"><a href="http://www.helloweba.com/view-blog-285.html"><%=@setting.head || "时间轴"%></a></h2>

<section id="cd-timeline" class="cd-container">
    
    <%@events.each do |event|%>
        <div class="cd-timeline-block">
            <a class="fancy_image" rel="group" href='<%=event.image_url(thumb: "?x-oss-process=image/resize,m_mfit,h_640,w_640")%>'>
            
    		<div class="cd-timeline-img cd-picture">
                    <%=image_tag event.image_url(thumb: '?x-oss-process=image/resize,m_mfit,h_60,w_60')%>
    		</div>
            </a>
            

    		<div class="cd-timeline-content">
    			<h2><%=event.title%></h2>
    			<p><%=event.desc%></p>
    			<span class="cd-date"><%=event.fire_at.strftime("%Y-%m-%d")%></span>
    		</div>
    	</div>
    <%end%>
    
	<div class="ad_76090"><script src="/js/ad_js/bd_76090.js" type="text/javascript"></script></div><br/>
</section>

<div id="footer">
    <%if @setting.footer_url.to_s.length==0%>
        <p><%=@setting.foot || "华丽的踢脚线"%></p>
    <%else%>
        <p><%=link_to (@setting.foot || "华丽的踢脚线"),@setting.footer_url %></p>
    <%end%>
</div>

<script>
    $(document).ready(function() {

    	/* This is basic - uses default settings */
	
    	$("a.fancy_image").fancybox();
    });
</script>

</body>
</html>

app/views/events/love.html.erb
<!doctype html>
<!--
    为中华之崛起 http://weizhonghuazhijueqi.com V1.0.20130216 => V1.1.20131022
    吕文翰_JohnLui 作品 http://lvwenhan.com
-->
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=1024" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title>季雯雯，我爱你</title>
	<meta name="keywords" content="吴鹏爱季雯雯" />
    <meta name="description" content="Storm ❤️ Judy" />
    <meta name="author" content="Storm" />

    <!--link href="http://fonts.googleapis.com/css?family=Open+Sans:regular,semibold,italic,italicsemibold|PT+Sans:400,700,400italic,700italic|PT+Serif:400,700,400italic,700italic" rel="stylesheet" /-->

    <link href="/css/impress.css" rel="stylesheet" />
</head>
<body class="impress-not-supported" onload="timedCount()">

<div class="fallback-message">
    <p>您的浏览器不支持HTML5，看不到<ddd> 3D </ddd>特效，肿么办？</p>
    <p><b>不用怕！</b></p><p>请下载最新的 <b>Chrome</b>, <b>Safari</b> 或者 <b>Firefox</b> 浏览器(360急速，搜狗的“极速模式”也可以哦~)</p>
</div>
<div id="impress">
    <div id="bored" class="step slide" data-x="-1000" data-y="-1500">
        <q><p>我给你看一个 </p><p><b> 很酷的 </b>网页版PPT</p></q>
    </div>

    <div class="step slide" data-x="0" data-y="-1500">
        <q>要再看敲下空格键看看  ^_^ </q>
    </div>

    <div class="step slide" data-x="1000" data-y="-1500">
        <q><p>什么鬼，这好像就是个PPT？</p><p>不对啊，<b> 右边 </b>好像没有了？！！</p></q>
    </div>

    <div id="title" class="step" data-x="0" data-y="0" data-scale="4">
        <span class="try">季雯雯</span>
        <h1>我爱你<sup>!</sup></h1>
        <!--span class="footnote"><sup>*</sup> no rhyme intended</span-->
    </div>

    <div id="its" class="step" data-x="850" data-y="3000" data-rotate="90" data-scale="5">
        <p>我们永远在一起！</p>
    </div>

    <div id="big" class="step" data-x="3500" data-y="2100" data-rotate="180" data-scale="6">
        <p>我们已经相爱了<b><span id="shijian"></span></b><span class="thoughts">秒</span></p>
    </div>


    <div id="tiny" class="step" data-x="2825" data-y="2325" data-z="-3000" data-rotate="300" data-scale="1">
        <p>时光<b> 易逝真爱 </b>永恒</p>
    </div>


    <div id="ing" class="step" data-x="3500" data-y="-850" data-rotate="270" data-scale="6">
        <p><span class="px60">你</span> <b class="positioning">喜欢</b><b class="rotating">做好吃的</b><br> <span class="px60">我</span> <b class="scaling">喜欢吃你做的好吃的</b><br /><xiaozi>你抓住了我的胃，也抓住了我的心</xiaozi></p>
    </div>

    <div id="imagination" class="step" data-x="6700" data-y="-300" data-scale="6">
        <p>我要大声说出 <br /><b class="imagination">我爱你！</b></p>
    </div>

    <div id="source" class="step" data-x="6300" data-y="2000" data-rotate="20" data-scale="4">
        <p>虽然好像不是很浪漫 <br /><b>但很程序猿风不是么</b></p>
    </div>

    <div id="one-more-thing" class="step" data-x="6000" data-y="4000" data-scale="2">
        <p>最后一句话想和你说......</p>
        
    </div>


    <div id="its-in-3d" class="step" data-x="6200" data-y="4300" data-z="-100" data-rotate-x="-90" data-rotate-y="90" data-scale="2">
        <p><span class="have">嫁</span> <span class="you">给</span> <span class="noticed">我,</span> <span class="its">好吗</span> <b>？</p>
    </div>

    <div id="overview" class="step" data-x="3000" data-y="1500" data-scale="10">
    </div>

</div>


<div class="hint">
    <p>请使用 "空格键" 或者 "↑ ↓ ← →" 操控</p>
</div>
<script>
if ("ontouchstart" in document.documentElement) { 
    document.querySelector(".hint").innerHTML = "<p>按下 \"← →\" 操控</p>";
}
</script>


<script src="/js/impress.js"></script>
<script src="/js/main.js" charset="utf-8"></script>
<script>impress().init();</script>


<div style="display: none">
</div>
</body>
</html>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @event.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fire_at) %>:</strong></dt>
  <dd><%= @event.fire_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @event.desc %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Events" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Events</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "设置", "/settings"  %></li>
            <li><%= link_to "事件", "/events"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/settings/_form.html.erb
<%= form_for @setting, :html => { :class => "form-horizontal setting" } do |f| %>

  <% if @setting.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @setting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :head, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :head, :class => 'form-control' %>
    </div>
    <%=f.error_span(:head) %>
  </div>
  <div class="form-group">
    <%= f.label :foot, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :foot, :class => 'form-control' %>
    </div>
    <%=f.error_span(:foot) %>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  
  <div class="form-group">
    <%= f.label :footer_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :footer_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:footer_url) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                settings_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/settings/edit.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/settings/index.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:head) %></th>
      <th><%= model_class.human_attribute_name(:foot) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to setting.id, setting_path(setting) %></td>
        <td><%= setting.head %></td>
        <td><%= setting.foot %></td>
        <td><%= setting.title %></td>
        <td><%=l setting.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_setting_path(setting), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settings/new.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/settings/show.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:head) %>:</strong></dt>
  <dd><%= @setting.head %></dd>
  <dt><strong><%= model_class.human_attribute_name(:foot) %>:</strong></dt>
  <dd><%= @setting.foot %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @setting.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:footer_url) %>:</strong></dt>
  <dd><%= @setting.footer_url %></dd>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              settings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_setting_path(@setting), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              setting_path(@setting),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>